### ISSUE TITLE
Proposal for some tutorial material to accompany sunraster

### ISSUE THREAD

**Issue by kakirastern** [sunpy/sunraster#141]
There is a need for some documentation in the form of, for example, some tutorial (series) to accompany the release of version 0.1 of `sunraster`. The goal is to serve general educational purposes for using `rasterpy` with IRIS data. Would like to see some elements contained in https://iris.lmsal.com/data.html to be included in the proposed documentation. 

The contents of that documentation can follow the structure of presentation of the original materials in the [old `IRISpy` docs](https://docs.sunpy.org/projects/irispy/en/latest/). 

Reference(s): 
1. https://iris.lmsal.com/itn26/itn26.pdf

**Comment by DanRyanIrish** [comment]
I think the documentation for ```sunsraster``` should be agnostic to the instrument that produces the data.  Also, ```sunraster``` does not provide the extensive data analysis workflow outlined in ITN 26.  Documentation is vital.  But perhaps you could specifically suggest what is lacking in the current [```sunraster``` documentation](https://github.com/sunpy/sunraster/tree/rasterpy/docs)?

**Comment by kakirastern** [comment]
One thing I noticed is some tutorial(s) could be added to the existing [`sunraster` documentation](https://github.com/sunpy/sunraster/tree/rasterpy/docs). And, I agree with you that the docs for `sunraster` should be agnostic to the instrument used. I am so used to the connection between `irispy` and `IRIS` data hence I made an assumption in my first comment. So yes, the new docs should include material pertaining to all major solar data types.

**Comment by kakirastern** [comment]
Let me also work on improving the [`sunraster` documentation](https://github.com/sunpy/sunraster/tree/rasterpy/docs) next. I will follow-up directly with some PR(s).

**Comment by kakirastern** [comment]
Hi @DanRyanIrish If you still remember there was an occasion during GSoC last summer when you assigned me to get some solar data to test some `IRISpy` function, I was actually having problems with the workflow and needed help managing the task. It is with this in mind that I opened this issue so that we will have some tutorial guiding the new user of solar data from fetching existing solar data (say such as IRIS data) to manipulating it with `sunraster`.

**Comment by DanRyanIrish** [comment]
Hi @kakirastern.  Thanks for your thoughts on this.  As helpful as a one-stop-guide showing all the stages of the workflow for solar physics analysis would be, I feel that this may be too large a scope for the ```sunraster``` docs.  It may be better suited to somewhere like the sunpy gallery.

My reasoning is that straying beyond ```sunraster``` tools has the potential to explode into a very detailed set of docs, only part of which is showing users how to use ```sunraster```.  This has a few potential drawbacks:
1. Readers will have to scroll through a lot more text to find what most will be looking for, i.e. instructions on how to use ```sunraster``` tools
2. The larger the docs, the more text to maintain and keep up-to-date when the code changes.
3. Docs to tools outside of ```sunraster``` are even harder to maintain and could lead to doc-update-only releases.
4. It is more likely that the docs will more quickly go out of date without our knowing.

Let's take your example of how to fetch solar data.  Let's say the Fido client changed in sunpy 2.0.  If no code had changed in ```sunraster``` a release would still be needed because we would be telling our users to follow a workflow that no longer works.  For packages maintained by people with not a lot of spare time, this is an unnecessary extra burden.  And what if ```sunraster``` worked  equally well with sunpy 1.0 and sunpy 2.0?  What should the tutorial say?  Should document both sunpy 1.0 and sunpy 2.0 Fido cases?  Again, this is extra maintenance.  And finally, if the feature we document is from a package with whom we don't have a personal relationship, e.g. ```scipy```, we may not know that our docs are out of date for some time because we didn't know they were changing things we'd documented.

Having said all this, if you feel the docs could be improved in how they explain the features in ```sunraster``` itself, this would be valuable information.  And in order to make sure you use your time most efficiently, let's discuss the issues you find here beforehand if you think they require significant rewrites.  If it's a small suggested change however, a PR may well be more efficient.

**Comment by kakirastern** [comment]
@DanRyanIrish Understood

**Comment by DanRyanIrish** [comment]
Btw, this tutorial idea is a good one and if you would like to work on one, I suggest you look through the sunpy docs and sunpy gallery and see if there is already something there that provides what you are looking for.  If not, talk with people on the sunpy riot channel and get some feedback about whether there's a space for such a tutorial there.

I just feel that most people's point of entry to using solar data in Python should be sunpy, not sunraster.  So that's where such a tutorial should live if it doesn't already exist there.
